Feature/configuration
xlasserre/target-mobile pull request #1
Opened 2018-05-22 20:12 UTC by missx

2018-05-23 15:48 UTC, bernabe9 requested changes
Excellent PR!

2018-05-23 15:48 UTC, bernabe9 commented on .eslintrc.js
> +// "off" or 0 - turn the rule off
We have our own `.eslintrc.js` file (https://github.com/rootstrap/react-native-base/blob/master/.eslintrc)

I would prefer if you use it to get used to our code style. Anyways, we can discuss other rules to add or remove :)

2018-05-23 15:48 UTC, bernabe9 commented on src/components/App.js
> +  constructor(props) {
`props` isn't necessary

2018-05-23 15:48 UTC, bernabe9 commented on src/components/App.js
> +class App extends React.Component {
I think that you don't need to extend this class to a React Component, just a class should work

2018-05-23 15:48 UTC, bernabe9 commented on src/containers/LoginScreen/index.js
> +import {
Write inline when the line doesnt exceed 80 characters

2018-05-23 15:48 UTC, bernabe9 commented on src/containers/LoginScreen/styles.js
> +    backgroundColor: '#EA0000',
Please create a styles constants file and store this color in it.

2018-05-23 18:57 UTC, missx commented on .eslintrc.js
> +// "off" or 0 - turn the rule off
Sure, I can use that!

2018-05-23 18:59 UTC, missx commented on src/components/App.js
> +class App extends React.Component {
Yeah, you are right, props and React.Component is not needed here.

2018-05-23 19:01 UTC, xlasserre commented on src/containers/LoginScreen/styles.js
> +    backgroundColor: '#EA0000',
Sure! I just had this to make sure I was showing the screen and everything is not blank, but I could do that now and leave the styles constants file ready to be used later.

2018-05-24 13:44 UTC, bernabe9 approved these changes

2018-05-24 13:49 UTC, matiasmansilla1989 approved these changes

2018-05-24 14:03 UTC, merged